### ISSUE TITLE
looking for 8.1 FIRM...

### ISSUE THREAD

**Issue by damnnfo** [AuroraWright/SafeA9LHInstaller#11]
It seems that new firm0 & firm0A9lh are required.
I tried to use google and also search them on that ISO site, but no result.
Could you pls give me some hint or a magic?
Thank you!

**Comment by Plailect** [comment]
The Guide ([Plailect/Guide](https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax))) now includes both precompiled payloads and firmware binaries for SafeA9LHInstaller v2.0, so this issue can be closed.

**Comment by xuefer** [comment]
hey Plailect. It's nice for you to have _v2 suffix in .zip filenames but you forgot to update zip filename in detail steps
Copy the a9lh folder from data_input.zip to the root of your SD Card
Copy and merge the a9lh folder from payload_input.zip to the root of your SD Card

**Comment by Plailect** [comment]
yep, fixed
