### ISSUE TITLE
Block pre-compiled firms that were created before the 2.0 update?

### ISSUE THREAD

**Issue by SirBeethoven** [AuroraWright/SafeA9LHInstaller#12]
Is there any way for SafeA9LHInstaller to detect and block precompiled firms before the 2.0 update? Maybe the app could detect where the bytes are placed?

**Comment by AuroraWright** [comment]
What? FIRMs are compiled by Nintendo... If you meant the stage payloads, the old ones are detected already with 2.0.1

**Comment by SirBeethoven** [comment]
Ok awesome!! Just didn't want people to be bricked!
