### ISSUE TITLE
CTRbootmanager9 not working

### ISSUE THREAD

**Issue by topkeksphagetti** [AuroraWright/SafeA9LHInstaller#13]
Ever since i've upgraded my a9lh v1 to v2.1, i couldn't get ctrbm9 to work, it just displays a blackscreen, if this issue dosen't get resolved, might as well downgrade back to v1.

**Comment by gilplay3000** [comment]
@topkeksphagetti try this version by @OperationNT: https://github.com/OperationNT414C/CtrBootManager/releases/tag/V7, it`s worked fine for me with v2 payloads

**Comment by topkeksphagetti** [comment]
Thank you so much!
