### ISSUE TITLE
Using A9Installer on 2.1 - garbled screen

### ISSUE THREAD

**Issue by gunner007cd** [AuroraWright/SafeA9LHInstaller#16]
I'll see if I can reproduce it, but when using the 2xRSA link to launch SafeA9LH, the bottom screen does the normal garbled screen, but never clears either screen and displays any information.

However, the application is actually loaded as pressing select will actually install, and pressing any other key will shut down the unit. (so you're sort of installing it blindly)

It does work though however, so it's just a minor thing.

**Comment by AuroraWright** [comment]
I can confirm this, but I have no idea how to fix it, I guess it would be the arm11.bin's responsibility to set up the screens correctly...
