### ISSUE TITLE
Many Bricks Caused By Installing Stage 2 With Incompatible Stage1

### ISSUE THREAD

**Issue by darkunderdog** [AuroraWright/SafeA9LHInstaller#2]
Any thoughts about removing the Stage 2 Option or making it more complex to do and bigger warnings? (Maybe something like press up, down, right,left, a - Like Decrypt9)?

I've seen over 4 bricks from people installing your fork of the noscreeninit Stage 2 when they had Stage 1 delebile

**Comment by mariogamer2** [comment]
Very Very bad idea...

The unlock sequence is  good idea.
