### ISSUE TITLE
2xrsa support

### ISSUE THREAD

**Issue by Sinrequilorios** [AuroraWright/SafeA9LHInstaller#20]
You could restore 2xrsa compatibility without removing the "OTPLess" support? Sorry for my bad English.

**Comment by AuroraWright** [comment]
2xrsa has been dropped for now because it leaves the ARM11 in an uncontrolled state, and I experienced memory corruption happening myself (luckily it happened before one of the hash checks, so I got an error). This makes it very dangerous.

**Comment by mariogamer2** [comment]
Is there anyway to had two version? Or this is an old/new 3ds issues?
