### ISSUE TITLE
Stuck at SafeA9LHInstaller screen

### ISSUE THREAD

**Issue by yuuhack** [AuroraWright/SafeA9LHInstaller#21]
N3DSXL hardmodded to 9.2.0.20u from 11.1.0.34u. At SafeA9LHInstaller v2.5 screen (menuhax entrypoint), it seems nothing happened eventhough pressed select button to full install. Other button (for shutdown )also not working. Using data input v3 & arm8loaderhax (noscreeninit)

**Comment by DeckOfNoobs** [comment]
Do you have the 10.0 firm in the A9LH folder?

**Comment by yuuhack** [comment]
firm0_100.bin? yes

**Comment by DeckOfNoobs** [comment]
That's odd...it may not be compatible with Menuhax. Try booting through browserhax.

**Comment by yuuhack** [comment]
Tried with browserhax also no success. Also done restored my original nand (11.1.0.34) to redo the guide started from the beginning but still stuck in this situation..

**Comment by yuuhack** [comment]
Ok. Sorry for the confusion caused.  This is really so dumb coming from me. The root cause was from the ribbon at L shoulder not install at the right position (should be backward). Then it caused the L shoulder always being pressed. This affect during installation a9lh and i cant select any button because the L button always being pressed! My bad.

**Comment by DeckOfNoobs** [comment]
Did you finally install A9LH?

**Comment by AuroraWright** [comment]
This was an hardware fault as they wrote.
