### ISSUE TITLE
Faces issue when trying to update using safeal9hinstaller v2.5.1

### ISSUE THREAD

**Issue by littlek4za** [AuroraWright/SafeA9LHInstaller#24]
It shows couldnt verift stage1 and/or stage 2 integrity!
Continuing might be dangerous!

If you would like to continue, press:
Up down.....

i follow the whole guide from https://github.com/Plailect/Guide/wiki/Updating-A9LH
and i get this issue, please advice. thank you.

i update because i saw a latest release from safeal9hinstaller 2.5.1, so i like to tried it out but this issue appear.

**Comment by theocmath** [comment]
I think you don't put the .sha in the a9lh files
