### ISSUE TITLE
Small issue unnecessarily causing bricks

### ISSUE THREAD

**Issue by ConnerP** [AuroraWright/SafeA9LHInstaller#25]
Obviously a great tool and thanks for the effort, but I help people out a lot on the discord chat for people hacking their 3ds's and this tool causes a lot of bricks from people using another console's OTP.bin. I've seen 5 people do this in the last week.

Would it be possible to make the default behaviour to NOT read the otp.bin file on the SD card? Also, I'm not sure if this is still the case but someone doing a n3ds installation on 9.2.0 got a brick because this tool used another consoles otp.bin on an otpless install.

**Comment by AuroraWright** [comment]
This was already done, but thanks to a major issue in 2xrsa the new release have memory corruption so people need to use the older ones
