### ISSUE TITLE
payload stage 1 doesn't exist or exceeds max size

### ISSUE THREAD

**Issue by AyyLmeow** [AuroraWright/SafeA9LHInstaller#28]
I get this issue every time I try to run safeal9hinstaller, I have gone through this:

 https://plailect.github.io/Guide/installing-arm9loaderhax

 guide over and over again and I'm sure that the correct files are in the correct folders, but it just won't run.

**Comment by AyyLmeow** [comment]
I'm on a downgraded N3ds 9.2

**Comment by AuroraWright** [comment]
Format the SD card and make sure the file payload_stage1.bin is in the a9lh folder. That error shows up if the file couldn't be read or it's too large, errors like these save you from a brick.

**Comment by noob3dsuser** [comment]
where do I get the payload because they're not anywhere in the downloads for the guide
