### ISSUE TITLE
Thanks for bricking my bros 3ds

### ISSUE THREAD

**Issue by M-1-RLG** [AuroraWright/SafeA9LHInstaller#36]
my bros 3ds got bricked thanks to you 200$ for no reason

**Comment by mariogamer2** [comment]
This is not the place ++ it's not aurora fault

**Comment by Razorzeto** [comment]
if you don't have the money to buy games, you shouldn't buy a console in first place :D

**Comment by james-d-elliott** [comment]
I could say something like 'Wasn't aware you didn't get warned about the risks or were forced to install it against your will". However, go to the IRC channel and someone may be able to help you if you're nice.

**Comment by designgears** [comment]
This is posted all over the guide.

"**Before beginning the guide, you must know the risks of 3DS hacking: EVERY time you modify your system, there is always the potential for an UNRECOVERABLE brick. They’re rare, but still a possibility so make sure you follow ALL directions EXACTLY.**"

http://www.rif.org/

**Comment by pbanj** [comment]
I think I speak for everyone when I say this, Get fucked. She has been working her ass off trying to figure out why this is happening, it's not her fault

**Comment by KilimIG** [comment]
thank God for the hooray emoji

**Comment by CrystaltheGlaceon** [comment]
This isn't the place to complain when you knowingly went into something that could break your system. It's your fault it broke, not the dev's, not Nintendo, and not the community. You knowingly went into this on your own
