### ISSUE TITLE
data_input_v4.zip  not working !!!

### ISSUE THREAD

**Issue by Mak22Khan** [AuroraWright/SafeA9LHInstaller#38]
Contents in data_input_v4.zip when copied to root of the sd card gives error of "firm0_100.bin missing or not correct size" when installing arm9loaderhax using select button on a New 3ds. However when contents of  data_input_v3.zip are used it runs perfectly. Although  data_input_v4.zip is recommended for New 3ds but it doesnt work instead  data_input_v3.zip is working. I have a New 3ds eur version.

**Comment by AuroraWright** [comment]
Don't use old releases

**Comment by Mak22Khan** [comment]
I downloaded it from the links in the guide.... Are they old releases ?
