### ISSUE TITLE
Issue with compilling modified installer v2.0.3

### ISSUE THREAD

**Issue by webvlad** [AuroraWright/SafeA9LHInstaller#44]
Hi!
Sorry for my noobish question/problem.
I have an o3ds with buggy Select button - it can work and more time it can't/
So i've stucked on the screen "Press SELECT for Full Installation".
I've tried to make corrections in installer.c - instead of waiting for Select button set Start_button. and tried to compile on linux.
There was errors connecting to gits, compiling 2xrsa,mset,rop.3ds and many others... so i retired and asking for your support (if it possible of course): is there any guide for compile such complex things or maybe someone compile "Start Edition" ?

**Comment by OctoNezd** [comment]
`make 2xrsa` would be OK for plailect guide. If there will be any error, download 2xrsa source to `2rxsa` folder

**Comment by TopKek69420** [comment]
did that work? if so, could you upload this version? I'm having the same problem

**Comment by OctoNezd** [comment]
Ok. https://www.dropbox.com/s/727yl2c2viewchm/out.zip?dl=0

**Comment by TopKek69420** [comment]
you are my saviour, thank you so much!

**Comment by OctoNezd** [comment]
![happy-oh-stop-it-you 1](https://cloud.githubusercontent.com/assets/15308404/21718028/a5e9bb3c-d425-11e6-91ae-2a980eaa8950.jpg)

**Comment by webvlad** [comment]
Thanks to OctoNezd - problem is solved.
