### ISSUE TITLE
[Question] Inject into 2.x sysnand?

### ISSUE THREAD

**Issue by dogtopus** [AuroraWright/SafeA9LHInstaller#5]
Since a9lh is somewhat system version independent, is it possible to make a 2xrsa-compatible payload that injects a9lh directly into a 2.x sysnand?

**Comment by dark-samus** [comment]
@dogtopus this is ALREADY 2xrsa compatible :P, just rename the arm9loaderhax.bin to arm9.bin, slap on SD card and install
