### ISSUE TITLE
 _ 

### ISSUE THREAD

**Issue by trilleplay** [AuroraWright/SafeA9LHInstaller#54]

**Comment by lilyuwuu** [comment]
http://3ds.guide for a full guide of installing a9lh

**Comment by trilleplay** [comment]
@togglechannelelsewhere I know! But in the README.MD file of this repo it states that random bricks are occurring on N3DS. I have no prob following http://3ds.guide But this is one crucial tool in the process in otherwords i want the software to be stable before I install it.

**Comment by ihaveamac** [comment]
these "random bricks" only happen using otpless, which the guide doesn't use right now
