### ISSUE TITLE
hi i need help with safea9lhinstaller

### ISSUE THREAD

**Issue by thepoodove** [AuroraWright/SafeA9LHInstaller#7]
i tried to use it  and it said this                 " An error occurred while loading the paypaload.
                                              Make sure your launcher is located at : /safeA9Installer.dat

                                                                              press key to continue "

please help asap also i used this tutorial https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)

**Comment by astronautlevel2** [comment]
This isn't a support forum. Post your question on the GBATemp thread: https://gbatemp.net/threads/safea9lhinstaller.419577/

**Comment by mariogamer2** [comment]
Please close it.
